### ISSUE TITLE
Body flag not working as intended

### ISSUE THREAD

**Issue by adik69** [projectdiscovery/httpx#116]
Simple to reproduce

echo "cdt0rvm3u711dfij7fqchzfbz25tti.burpcollaborator.net" |httpx -x POST -body 'proxy=https://cdt0rvm3u711dfij7fqchzfbz25tti.burpcollaborator.net'

Check Your Requests in your Collaborator!

Additional characters have been added here.

**Comment by bauthard** [comment]
Example of post request:- 

```http
POST / HTTP/1.1
Host: 2befm9bzd996j4ao3hky5jwkbbh25r.burpcollaborator.net
User-Agent: httpx - Open-source project (github.com/projectdiscovery/httpx)
Transfer-Encoding: chunked
Accept-Charset: utf-8
Accept-Encoding: gzip
Connection: close

41
proxy=https://cdt0rvm3u711dfij7fqchzfbz25tti.burpcollaborator.net
0
```

**Comment by Mzack9999** [comment]
When the content-length is unknown we use `Transfer-Encoding: chunked` that requires to specify the body size (`41`) and at the end the null character (`0`) in order to allow the server to know exactly where the body starts and the amount of bytes to read. With the linked PR it would work as expected.

**Comment by bauthard** [comment]
@adik69 this is now fixed in the master code.
