### ISSUE TITLE
generate HAR file

### ISSUE THREAD

**Issue by j4i4i** [projectdiscovery/httpx#1167]
Does the httpx have the ability to generate HAR file?
like browsertime (https://github.com/sitespeedio/browsertime)
-- browsertime --silent --headless -n 1 --chrome.collectPerfLog

**Comment by Mzack9999** [comment]
This will be supported with https://github.com/projectdiscovery/proxify/issues/482 since it seems more a functionality for a crawler/proxy interceptor. Once it's implemented you can easily use `-proxy http://proxify:xxxx` with httpx or any other tool.

I'm closing the issue as it will be worked within `proxify`
