### ISSUE TITLE
[bug]ver 1.3.7, Some functions do not work correctly and output results

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/httpx#1463]
Some functions do not work correctly and output results
```
httpx -u https://ttblaze.iifl.com:4006  -websocket -method -server -status-code -location -http2  -pipeline -td -json

```
-websocket not work
<img width="662" alt="image" src="https://github.com/projectdiscovery/httpx/assets/18223385/ecea68a5-3d48-4f91-980e-131ba9da4fc7">

<img width="963" alt="image" src="https://github.com/projectdiscovery/httpx/assets/18223385/9aade628-195c-492e-9875-74fbb122ce68">

-pipeline not work
<img width="985" alt="image" src="https://github.com/projectdiscovery/httpx/assets/18223385/d7322929-6e52-479a-87f5-3c2b48508519">

**Comment by acidvegas** [comment]
Since no one is replying to you:
https://github.com/projectdiscovery/httpx/issues/1498

They seem to think using "jq" or some 3rd party shit is the solution.
Its pretty lame that a basic feature almost EVERY SINGLE SCANNER ON THE INTERNET HAS which is custom json output.


As it stands right now, you cant control some of the elements with the JSON output (why? I have no fucking idea)

**Comment by hktalent** [comment]
@acidvegas I understand your mood and difficulties
JSON output does have some difficulties and challenges in unified output of multi-task results in golang.

**Comment by ehsandeep** [comment]
@acidvegas I understand your frustration related to handling jsonl data, we suggested workaround and have created issue in the team backlogs for future as any change related to handling jsonl will be applicable to all pd projects not only httpx, in the meantime can you not comment on multiple / unrelated issues on GitHub? as this issue is related to bug with `-websocket`, `-pipeline` probing option.

**Comment by hktalent** [comment]
@ehsandeep 
v1.3.8

Still not getting the expected results
At least for this goal, I'm pretty sure there are websockets and pipelines, but I didn't get such a result.

**Comment by acidvegas** [comment]
@hktalent apparently JSON is really advanced stuff that is difficult to manage XD

**Comment by Mzack9999** [comment]
@acidvegas The issue is totally unrelated to JSON. The reported issue is about network probing to detect websockets (via http upgrade) and pipelining (via idempotent http requests).

Can you mention which scanner has custom json output? At the time of implementation it was opted for a static structure, as no major scanner had such capability, maybe we missed something.
