### ISSUE TITLE
[FTL] Could not create httpx instance: could not create resolver cache: messages

### ISSUE THREAD

**Issue by ranlo** [projectdiscovery/httpx#1535]
### Current Behavior:
getting repeated messages saying
[FTL] Could not create httpx instance: could not create resolver cache: mkdir /var/folders/gq/<redacted>/T/httpx<seemingly random number>: no space left on device
My OS disk was running low on space. I left a script containing httpx running overnight, and got lots of these messages.

the /var/folders/gq/<redacted>/T directory contains lots of https<random> directories created at various hours over the night, conaining

-rw-r--r--  1 user  staff     0 Jan 14 22:57 LOCK
-rw-r--r--  1 user  staff    16 Jan 14 22:57 CURRENT
-rw-r--r--  1 user  staff    54 Jan 14 22:57 MANIFEST-000000
-rw-r--r--  1 user  staff   360 Jan 14 22:57 LOG
-rw-r--r--  1 user  staff  5346 Jan 14 22:57 000001.log

**Comment by dogancanbakir** [comment]
The error message you're seeing is due to the disk running out of space. The `httpx` uses [hmap](https://github.com/projectdiscovery/hmap) which creates temporary directories for caching. When the disk is full, it can't create these directories, hence the error.

The [hmap](https://github.com/projectdiscovery/hmap) has a cleanup mechanism that removes old temporary directories. However, it seems like this cleanup process is not keeping up with the rate of directory creation in your case.

You can try the following solutions:

1. Increase your disk space.
2. Reduce the frequency of httpx runs to allow the cleanup process to catch up. /shrug
3. Manually delete the temporary directories in /var/folders/gq//T/.


Let us know if you have further questions.
