### ISSUE TITLE
[feature] Regex extractor support

### ISSUE THREAD

**Issue by b3r1ch** [projectdiscovery/httpx#173]
some sites have no title info in home page or can not use default regexp to match title
`(?im)<\s*title.*>(.*?)<\s*/\s*title>`
so, how to custom the default regexp?

maybe httpx need new param like this:

```bash
cat domains.txt | httpx -path /SiteInfo -title-regex "Title\":\"(.*?)\"" -title
```

**Comment by team-projectdiscovery** [comment]
Hi @b3r1ch, 

Currently, we do have `match-regex` flag that supports matching but not extraction, so we can think about it if it's a good idea or not as we have another project called [nuclei](https://github.com/projectdiscovery/nuclei) that supports more controls/extractors on the response data so that might fits better for this use case? also is it possible to share an example if we can improve our existing title regex?

**Comment by b3r1ch** [comment]
hi,look here #175

**Comment by team-projectdiscovery** [comment]
As per comment on https://github.com/projectdiscovery/httpx/pull/175
