### ISSUE TITLE
Getting "Could not open/create output file 'filtered_error_page.json"

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/httpx#1821]
Is there a way to change the HTTPX temp directory, running lambda got  "Could not open/create output file 'filtered_error_page.json'" I'm using -fep option. 

posted at https://discord.com/channels/695645237418131507/716605549923270717/1260636102734250157

**Comment by hoacks** [comment]
Here the details, try to run httpx from a aws lambda, but as you may know, you only have write access to a tmp/ folder, when trying to run the -fep option, httpx tries to create the filtered_error_page.json file but failed because can't write to disk. In the mean time i'm filter with regex but doing it manually case by case. Would be very usefull to change specify the temp folder and use the -fep option to do this automatically. Thanks, you rock!

**Comment by ehsandeep** [comment]
@hoacks this is fixed in latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.7

Now you can specify custom file path for error file.
