### ISSUE TITLE
unable to use internt while running httpx tool

### ISSUE THREAD

**Issue by balook** [projectdiscovery/httpx#44]
i ranned httpx tool for 1000 urls and concurrently i tried to browse in browser....but im unable to browse anything .. i faced the same issue when masscan, ...i think the tool is using so many threads...... but when i used ffuf with many threads too i can browse and can able to access internet...once look into this. i juse didnt used any threads in httpx but also ....im unable to browse...

**Comment by bauthard** [comment]
Hey @balook, 

`httpx` uses only 50 threads on default run, so that shouldn't be an issue on any system, without any relevant information I'm not sure we can do any help about this. 

You can try to monitor your systems **bandwidth/RAM/CPUs** uses to explore the root cause. 

Also to be sure, you can use `httpx -threads 1` which is same opening an URL or making `cURL` request from your system.
