### ISSUE TITLE
Sometime with large input like 100000 domains it stuck 

### ISSUE THREAD

**Issue by yashanand** [projectdiscovery/httpx#61]
![image](https://user-images.githubusercontent.com/21155589/89559670-9f8d7100-d833-11ea-9156-f1cdcf1ffe4c.png)

Note:-My internet is working properly

**Comment by bauthard** [comment]
Hi @yashanand, 

Thank you for reporting this, I assume this is not about numbers, but any or few specific hosts which behaves/respond in an unexpected way, so in order to fix those cases we need to know which input causing the issue, you can reach out to us on discord if you willing to share the list and we will look into this, or attach here if it's public information.

**Comment by bauthard** [comment]
@Mzack9999 this might be related to `chaos -d google.com | httpx`

**Comment by yashanand** [comment]
ok I will ping you on discord

**Comment by bauthard** [comment]
Hey @yashanand, 

it worked for me, I tested twice and completed after

```
time httpx -l shuff.txt

real	118m6.977s
user	5m15.380s
sys	4m0.228s
``` 

Are you sure you waited enough time before coming to this conclusion?

**Comment by Mzack9999** [comment]
This is not reproducible after almost a dozen of runs. Feel free to reopen if the problem persists.
