### ISSUE TITLE
Option to list all JSON output keys name

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/httpx#750]
### Please describe your feature request:
A new option to list all the json output field keys name which can be further used with matchers / filters.

```yaml
   -ldv, -list-dsl-variables  list json output field keys name that support dsl matcher/filter
```

```console
httpx -ldv

timestamp
csp
domains
hash
body_md5
body_mmh3
body_sha256
body_simhash
header_md5
header_mmh3
header_sha256
header_simhash
port
url
input
location
scheme
webserver
content_type
method
host
path
time
a
words
lines
status_code
content_length
failed
body
header
request
```

### Describe the use case of this feature:
New options which will support new dsl matcher/filter option using these keys name.

**Comment by forgedhallpass** [comment]
I think the `-list-dsl` flag name is confusing, because it doesn't refer to DSL function signatures as in other tools (nuclei and I think also proxify), but only shows the variable/constants that can be referenced from a DSL context. For this reason I would recommend renaming it to something like `-list-dsl-variables` or `-list-dsl-attributes`.
