### ISSUE TITLE
resume flag overwrites output file

### ISSUE THREAD

**Issue by minispooner** [projectdiscovery/httpx#792]
### httpx version:
v1.2.4

### Current Behavior:
when passing -resume and -o OUTPUT_FILE flags, httpx clears and overwrites the OUTPUT_FILE contents

### Expected Behavior:
when passing -resume and -o OUTPUT_FILE flags, httpx should NOT clear and overwrite the OUTPUT_FILE contents. instead, httpx should APPEND to the OUTPUT_FILE contents (but not write the application header display again, simply pick up where it left off).

### Steps To Reproduce:
# setup dummy hosts file
echo "example.com" > five_hosts.txt
echo "www.google.com" >> five_hosts.txt
echo "www.facebook.com" >> five_hosts.txt
echo "example2.com" >> five_hosts.txt
echo "www.twitter.com" >> five_hosts.txt
# setup resume.cfg file to pretend like httpx has already run once
echo "resume_from=www.facebook.com" > resume.cfg
echo "index=3" >> resume.cfg # not sure if index is 0-based or 1-based...
# setup a fake previous* run output file
echo "this text will no longer appear" > out.txt
# run 2nd attempt of httpx
cat five_hosts.txt | httpx -o out.txt -resume
cat out.txt | grep "this text will no longer appear"
# text not found using grep, showing that the -resume flag overwrites previous output data instead of appending to it. "resume" should intuitively append, not overwrite
# I just ran these steps and validated the steps to reproduce work as described above.

screenshot below
![image](https://user-images.githubusercontent.com/8799336/193639883-819a3a79-94f8-47ce-ba86-201c5c2e9656.png)

**Comment by ibitebyt3s** [comment]
Took a look at this and got an unfinished idea but ran out of time today.

1. Add extra if else block(s?) (nested?) that opens the file pointer with the `os.O_APPEND` flag near this `if` block where it's always creating a new empty file. Something like `f, err = os.OpenFile(r.options.Output, os.O_APPEND)` migth be part of the code. 
https://github.com/projectdiscovery/httpx/blob/f2cd5b835348c5563c4c018dc2ed414d82ccf249/runner/runner.go#L562
2. If appending to it, add a check to handle the case were the file doesn't exist. I thought that exiting the program might be the best way to do it instead of continuing execution. 
3. Keep in mind what else I could have missed. 
---
I'll notify in this thread if I begin to work on it. 
Found [this blog post](https://zetcode.com/golang/file/) with code snippets, that was a useful refresher of golang file handling.
