### ISSUE TITLE
Unable to parse when the returned packet is not in normal http format

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/httpx#960]
### httpx version:

v1.2.6

### Current Behavior:

```
[DBG] Failed 'http://*.*.*.*:8080': GET http://*.*.*.*:8080 giving up after 1 attempts: Get "http://*.*.*.*:8080": net/http: HTTP/1.x transport connection broken: malformed MIME header: missing colon: "user\""
```

```
[DBG] Failed 'http://*.*.*.*:8080': invalid header line: "user\"\r\n"
```

<img width="1515" alt="Snipaste_2023-02-06_01-10-12" src="https://user-images.githubusercontent.com/18167071/216833730-8aef4099-b8f7-4a7c-b1cc-fda684a9cb7f.png">

![Snipaste_2023-02-06_01-08-29](https://user-images.githubusercontent.com/18167071/216833648-d848dd35-af00-47df-aa0d-35a5c3ef37d1.png)

### Expected Behavior:

The target is accessible and should have normal result output

### Steps To Reproduce:

1. fofa query: `"wf2411" && port="8080"`
2. `echo "*.*.*.*:8080" | httpx -debug -unsafe`

**Comment by Mzack9999** [comment]
@No-Github Thanks for opening this issue. Unfortunately the standard library enforces strong validation on http protocol. Probably this will be indirectly fixed with https://github.com/projectdiscovery/rawhttp/pull/112

**Comment by Mzack9999** [comment]
Although it is possible in some hacky way to override the internal `net/textproto/reader.goreadMIMEHeader` via linking after testing, it seems pretty much unreliable as the rest of the response fail to be parsed, and numerous runtime errors are introduced. Closing as not planned for the time being, it will be indirectly fixed with https://github.com/projectdiscovery/rawhttp/pull/112 fallback mechanism
